# Generated by Django 2.2.5 on 2019-10-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0018_auto_20191011_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
                ('userPrice', models.FloatField()),
                ('counterPrice', models.FloatField(blank=True, null=True)),
                ('halfPaid', models.BooleanField(default=False)),
                ('fullPaid', models.BooleanField(default=False)),
                ('userAssignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.UserAssignment')),
            ],
        ),
    ]
