# Generated by Django 2.2.5 on 2019-09-26 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('averagePrice', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRequested', models.DateTimeField(auto_now_add=True)),
                ('dateCompleted', models.DateTimeField()),
                ('desc', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('userPrice', models.FloatField()),
                ('counterPrice', models.FloatField(blank=True, null=True)),
                ('halfPaid', models.BooleanField(default=False)),
                ('fullPaid', models.BooleanField(default=False)),
                ('assignmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('necessary', models.BooleanField(default=False)),
                ('assignmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType')),
            ],
        ),
    ]
