# Generated by Django 2.2.5 on 2019-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassignment',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
