# Generated by Django 2.2.5 on 2019-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20190926_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
