# Generated by Django 2.2.5 on 2019-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20190926_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
