# Generated by Django 2.2.2 on 2019-09-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_userassignment_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
