# Generated by Django 2.2.5 on 2019-09-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_userassignment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
