# Generated by Django 2.2.5 on 2019-09-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_userassignment_expecteddat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassignment',
            old_name='expectedDat',
            new_name='expectedDate',
        ),
    ]
