# Generated by Django 2.2.5 on 2019-10-02 21:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20190930_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassignment',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
