# Generated by Django 2.2.5 on 2019-10-05 14:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20191002_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttype',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
