# Generated by Django 2.2.5 on 2019-10-05 16:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20191005_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', ckeditor.fields.RichTextField()),
                ('must', models.BooleanField(default=False)),
                ('assignmentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentType')),
            ],
        ),
    ]
