# Generated by Django 2.2.5 on 2019-10-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='citation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userassignment',
            name='font',
            field=models.CharField(default='Times New Roman', max_length=100),
        ),
        migrations.AddField(
            model_name='userassignment',
            name='fontSize',
            field=models.FloatField(default=12.0),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='assignmentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.UserAssignment'),
        ),
    ]
