# Generated by Django 2.2.5 on 2019-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_auto_20191005_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
