# Generated by Django 2.2.5 on 2019-10-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_assignmentmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmedia',
            name='file',
            field=models.FileField(upload_to='assignments/'),
        ),
    ]
