# Generated by Django 2.2.5 on 2019-10-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0016_assignmentchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentchange',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
