# Generated by Django 2.2.5 on 2019-10-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_assignmentchange_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassignment',
            name='counterPrice',
        ),
        migrations.RemoveField(
            model_name='userassignment',
            name='fullPaid',
        ),
        migrations.RemoveField(
            model_name='userassignment',
            name='halfPaid',
        ),
        migrations.RemoveField(
            model_name='userassignment',
            name='userPrice',
        ),
    ]
