# Generated by Django 2.2.5 on 2019-10-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0018_auto_20191011_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmedia',
            name='userAssignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.UserAssignment'),
        ),
    ]
